# YAML configuration for PostgreSQL Service deployment. This service will live in the test-lab namespace
apiVersion: v1
kind: Service

metadata:
  name: postgres
  namespace: test-lab

spec:
  selector:
    app: postgres

ports:
- port: 5432
  targetPort: 5432